allennlp:
  - 'optuna_integration/allennlp/**'
  - 'tests/allennlp/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

botorch:
  - 'optuna_integration/botorch/**'
  - 'tests/botorch/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

catboost:
  - 'optuna_integration/catboost/**'
  - 'tests/catboost/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

chainer:
  - 'optuna_integration/chainer/**'
  - 'tests/chainer/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

chainermn:
  - 'optuna_integration/chainermn/**'
  - 'tests/chainermn/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

cma:
  - 'optuna_integration/cma/**'
  - 'tests/cma/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

dask:
  - 'optuna_integration/dask/**'
  - 'tests/dask/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

fastaiv2:
  - 'optuna_integration/fastaiv2/**'
  - 'tests/fastaiv2/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

keras:
  - 'optuna_integration/keras/**'
  - 'tests/keras/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

lightgbm:
  - 'optuna_integration/lightgbm/**'
  - 'tests/lightgbm/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

mlflow:
  - 'optuna_integration/mlflow/**'
  - 'tests/mlflow/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

mxnet:
  - 'optuna_integration/mxnet/**'
  - 'tests/mxnet/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

pytorch_distributed:
  - 'optuna_integration/pytorch_distributed/**'
  - 'tests/pytorch_distributed/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

pytorch_ignite:
  - 'optuna_integration/pytorch_ignite/**'
  - 'tests/pytorch_ignite/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

pytorch_lightning:
  - 'optuna_integration/pytorch_lightning/**'
  - 'tests/pytorch_lightning/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

shap:
  - 'optuna_integration/shap/**'
  - 'tests/shap/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

sklearn:
  - 'optuna_integration/sklearn/**'
  - 'tests/sklearn/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

skorch:
  - 'optuna_integration/skorch/**'
  - 'tests/skorch/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

tensorboard:
  - 'optuna_integration/tensorboard/**'
  - 'tests/tensorboard/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

tensorflow:
  - 'optuna_integration/tensorflow/**'
  - 'tests/tensorflow/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

tfkeras:
  - 'optuna_integration/tfkeras/**'
  - 'tests/tfkeras/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

wandb:
  - 'optuna_integration/wandb/**'
  - 'tests/wandb/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'

xgboost:
  - 'optuna_integration/xgboost/**'
  - 'tests/xgboost/**'
  - '.github/workflows/checks.yml'
  - '.github/workflows/checks_template.yml'
  - '.github/file-filters.yml'
